/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

S  pS(FILE *inp);
S psS(const char *str);
Block  pBlock(FILE *inp);
Block psBlock(const char *str);
CMDS  pCMDS(FILE *inp);
CMDS psCMDS(const char *str);
CMD  pCMD(FILE *inp);
CMD psCMD(const char *str);
ATB  pATB(FILE *inp);
ATB psATB(const char *str);
EXP  pEXP(FILE *inp);
EXP psEXP(const char *str);
SE  pSE(FILE *inp);
SE psSE(const char *str);
OPerL  pOPerL(FILE *inp);
OPerL psOPerL(const char *str);
OPerA  pOPerA(FILE *inp);
OPerA psOPerA(const char *str);
OPL  pOPL(FILE *inp);
OPL psOPL(const char *str);
CLAUDDIZ  pCLAUDDIZ(FILE *inp);
CLAUDDIZ psCLAUDDIZ(const char *str);
RECEBA  pRECEBA(FILE *inp);
RECEBA psRECEBA(const char *str);
ATE  pATE(FILE *inp);
ATE psATE(const char *str);
FAZAI  pFAZAI(FILE *inp);
FAZAI psFAZAI(const char *str);
VALUE  pVALUE(FILE *inp);
VALUE psVALUE(const char *str);
Type  pType(FILE *inp);
Type psType(const char *str);
VET  pVET(FILE *inp);
VET psVET(const char *str);
STRUCT  pSTRUCT(FILE *inp);
STRUCT psSTRUCT(const char *str);
HeteroElements  pHeteroElements(FILE *inp);
HeteroElements psHeteroElements(const char *str);
HeteroElement  pHeteroElement(FILE *inp);
HeteroElement psHeteroElement(const char *str);
FUNC  pFUNC(FILE *inp);
FUNC psFUNC(const char *str);
GOTO  pGOTO(FILE *inp);
GOTO psGOTO(const char *str);
LABEL  pLABEL(FILE *inp);
LABEL psLABEL(const char *str);
ConjInt  pConjInt(FILE *inp);
ConjInt psConjInt(const char *str);
ConjReal  pConjReal(FILE *inp);
ConjReal psConjReal(const char *str);
ConjString  pConjString(FILE *inp);
ConjString psConjString(const char *str);
CONST  pCONST(FILE *inp);
CONST psCONST(const char *str);
POINT  pPOINT(FILE *inp);
POINT psPOINT(const char *str);

#endif
