/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printS(S p)
{
  _n_ = 0;
  bufReset();
  ppS(p, 0);
  return buf_;
}
char *printBlock(Block p)
{
  _n_ = 0;
  bufReset();
  ppBlock(p, 0);
  return buf_;
}
char *printCMDS(CMDS p)
{
  _n_ = 0;
  bufReset();
  ppCMDS(p, 0);
  return buf_;
}
char *printCMD(CMD p)
{
  _n_ = 0;
  bufReset();
  ppCMD(p, 0);
  return buf_;
}
char *printATB(ATB p)
{
  _n_ = 0;
  bufReset();
  ppATB(p, 0);
  return buf_;
}
char *printEXP(EXP p)
{
  _n_ = 0;
  bufReset();
  ppEXP(p, 0);
  return buf_;
}
char *printSE(SE p)
{
  _n_ = 0;
  bufReset();
  ppSE(p, 0);
  return buf_;
}
char *printOPerL(OPerL p)
{
  _n_ = 0;
  bufReset();
  ppOPerL(p, 0);
  return buf_;
}
char *printOPerA(OPerA p)
{
  _n_ = 0;
  bufReset();
  ppOPerA(p, 0);
  return buf_;
}
char *printOPL(OPL p)
{
  _n_ = 0;
  bufReset();
  ppOPL(p, 0);
  return buf_;
}
char *printCLAUDDIZ(CLAUDDIZ p)
{
  _n_ = 0;
  bufReset();
  ppCLAUDDIZ(p, 0);
  return buf_;
}
char *printRECEBA(RECEBA p)
{
  _n_ = 0;
  bufReset();
  ppRECEBA(p, 0);
  return buf_;
}
char *printATE(ATE p)
{
  _n_ = 0;
  bufReset();
  ppATE(p, 0);
  return buf_;
}
char *printFAZAI(FAZAI p)
{
  _n_ = 0;
  bufReset();
  ppFAZAI(p, 0);
  return buf_;
}
char *printVALUE(VALUE p)
{
  _n_ = 0;
  bufReset();
  ppVALUE(p, 0);
  return buf_;
}
char *printType(Type p)
{
  _n_ = 0;
  bufReset();
  ppType(p, 0);
  return buf_;
}
char *printVET(VET p)
{
  _n_ = 0;
  bufReset();
  ppVET(p, 0);
  return buf_;
}
char *printSTRUCT(STRUCT p)
{
  _n_ = 0;
  bufReset();
  ppSTRUCT(p, 0);
  return buf_;
}
char *printHeteroElements(HeteroElements p)
{
  _n_ = 0;
  bufReset();
  ppHeteroElements(p, 0);
  return buf_;
}
char *printHeteroElement(HeteroElement p)
{
  _n_ = 0;
  bufReset();
  ppHeteroElement(p, 0);
  return buf_;
}
char *printFUNC(FUNC p)
{
  _n_ = 0;
  bufReset();
  ppFUNC(p, 0);
  return buf_;
}
char *printGOTO(GOTO p)
{
  _n_ = 0;
  bufReset();
  ppGOTO(p, 0);
  return buf_;
}
char *printLABEL(LABEL p)
{
  _n_ = 0;
  bufReset();
  ppLABEL(p, 0);
  return buf_;
}
char *printConjInt(ConjInt p)
{
  _n_ = 0;
  bufReset();
  ppConjInt(p, 0);
  return buf_;
}
char *printConjReal(ConjReal p)
{
  _n_ = 0;
  bufReset();
  ppConjReal(p, 0);
  return buf_;
}
char *printConjString(ConjString p)
{
  _n_ = 0;
  bufReset();
  ppConjString(p, 0);
  return buf_;
}
char *printCONST(CONST p)
{
  _n_ = 0;
  bufReset();
  ppCONST(p, 0);
  return buf_;
}
char *printPOINT(POINT p)
{
  _n_ = 0;
  bufReset();
  ppPOINT(p, 0);
  return buf_;
}
char *showS(S p)
{
  _n_ = 0;
  bufReset();
  shS(p);
  return buf_;
}
char *showBlock(Block p)
{
  _n_ = 0;
  bufReset();
  shBlock(p);
  return buf_;
}
char *showCMDS(CMDS p)
{
  _n_ = 0;
  bufReset();
  shCMDS(p);
  return buf_;
}
char *showCMD(CMD p)
{
  _n_ = 0;
  bufReset();
  shCMD(p);
  return buf_;
}
char *showATB(ATB p)
{
  _n_ = 0;
  bufReset();
  shATB(p);
  return buf_;
}
char *showEXP(EXP p)
{
  _n_ = 0;
  bufReset();
  shEXP(p);
  return buf_;
}
char *showSE(SE p)
{
  _n_ = 0;
  bufReset();
  shSE(p);
  return buf_;
}
char *showOPerL(OPerL p)
{
  _n_ = 0;
  bufReset();
  shOPerL(p);
  return buf_;
}
char *showOPerA(OPerA p)
{
  _n_ = 0;
  bufReset();
  shOPerA(p);
  return buf_;
}
char *showOPL(OPL p)
{
  _n_ = 0;
  bufReset();
  shOPL(p);
  return buf_;
}
char *showCLAUDDIZ(CLAUDDIZ p)
{
  _n_ = 0;
  bufReset();
  shCLAUDDIZ(p);
  return buf_;
}
char *showRECEBA(RECEBA p)
{
  _n_ = 0;
  bufReset();
  shRECEBA(p);
  return buf_;
}
char *showATE(ATE p)
{
  _n_ = 0;
  bufReset();
  shATE(p);
  return buf_;
}
char *showFAZAI(FAZAI p)
{
  _n_ = 0;
  bufReset();
  shFAZAI(p);
  return buf_;
}
char *showVALUE(VALUE p)
{
  _n_ = 0;
  bufReset();
  shVALUE(p);
  return buf_;
}
char *showType(Type p)
{
  _n_ = 0;
  bufReset();
  shType(p);
  return buf_;
}
char *showVET(VET p)
{
  _n_ = 0;
  bufReset();
  shVET(p);
  return buf_;
}
char *showSTRUCT(STRUCT p)
{
  _n_ = 0;
  bufReset();
  shSTRUCT(p);
  return buf_;
}
char *showHeteroElements(HeteroElements p)
{
  _n_ = 0;
  bufReset();
  shHeteroElements(p);
  return buf_;
}
char *showHeteroElement(HeteroElement p)
{
  _n_ = 0;
  bufReset();
  shHeteroElement(p);
  return buf_;
}
char *showFUNC(FUNC p)
{
  _n_ = 0;
  bufReset();
  shFUNC(p);
  return buf_;
}
char *showGOTO(GOTO p)
{
  _n_ = 0;
  bufReset();
  shGOTO(p);
  return buf_;
}
char *showLABEL(LABEL p)
{
  _n_ = 0;
  bufReset();
  shLABEL(p);
  return buf_;
}
char *showConjInt(ConjInt p)
{
  _n_ = 0;
  bufReset();
  shConjInt(p);
  return buf_;
}
char *showConjReal(ConjReal p)
{
  _n_ = 0;
  bufReset();
  shConjReal(p);
  return buf_;
}
char *showConjString(ConjString p)
{
  _n_ = 0;
  bufReset();
  shConjString(p);
  return buf_;
}
char *showCONST(CONST p)
{
  _n_ = 0;
  bufReset();
  shCONST(p);
  return buf_;
}
char *showPOINT(POINT p)
{
  _n_ = 0;
  bufReset();
  shPOINT(p);
  return buf_;
}
void ppS(S p, int _i_)
{
  switch(p->kind)
  {
  case is_Sst:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("main");
    renderS("Claud");
    renderC('(');
    renderS("kd");
    renderS("gaucho");
    renderC(')');
    ppBlock(p->u.sst_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing S!\n");
    exit(1);
  }
}

void ppBlock(Block p, int _i_)
{
  switch(p->kind)
  {
  case is_LBlock:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('{');
    ppCMDS(p->u.lblock_.cmds_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Block!\n");
    exit(1);
  }
}

void ppCMDS(CMDS p, int _i_)
{
  switch(p->kind)
  {
  case is_CMDSCMD:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCMD(p->u.cmdscmd_.cmd_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDS1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCMD(p->u.cmds1_.cmd_, 0);
    ppCMDS(p->u.cmds1_.cmds_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CMDS!\n");
    exit(1);
  }
}

void ppCMD(CMD p, int _i_)
{
  switch(p->kind)
  {
  case is_CMDATB:
    if (_i_ > 0) renderC(_L_PAREN);
    ppATB(p->u.cmdatb_.atb_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDSE:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSE(p->u.cmdse_.se_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDATE:
    if (_i_ > 0) renderC(_L_PAREN);
    ppATE(p->u.cmdate_.ate_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDFAZAI:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFAZAI(p->u.cmdfazai_.fazai_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDCLAUDDIZ:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCLAUDDIZ(p->u.cmdclauddiz_.clauddiz_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDRECEBA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppRECEBA(p->u.cmdreceba_.receba_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDCONST:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCONST(p->u.cmdconst_.const_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDVET:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVET(p->u.cmdvet_.vet_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDFUNC:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFUNC(p->u.cmdfunc_.func_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDGOTO:
    if (_i_ > 0) renderC(_L_PAREN);
    ppGOTO(p->u.cmdgoto_.goto_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDLABEL:
    if (_i_ > 0) renderC(_L_PAREN);
    ppLABEL(p->u.cmdlabel_.label_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDSTRUCT:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSTRUCT(p->u.cmdstruct_.struct_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDPOINT:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPOINT(p->u.cmdpoint_.point_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CMD!\n");
    exit(1);
  }
}

void ppATB(ATB p, int _i_)
{
  switch(p->kind)
  {
  case is_ATB1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.atb1_.type_, 0);
    ppIdent(p->u.atb1_.ident_, 0);
    renderC('=');
    ppVALUE(p->u.atb1_.value_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ATB2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.atb2_.type_, 0);
    ppIdent(p->u.atb2_.ident_, 0);
    renderC('=');
    ppEXP(p->u.atb2_.exp_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ATB!\n");
    exit(1);
  }
}

void ppEXP(EXP p, int _i_)
{
  switch(p->kind)
  {
  case is_EXP1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVALUE(p->u.exp1_.value_1, 0);
    ppOPerA(p->u.exp1_.opera_, 0);
    ppVALUE(p->u.exp1_.value_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EXP2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppEXP(p->u.exp2_.exp_, 0);
    ppOPerA(p->u.exp2_.opera_, 0);
    ppVALUE(p->u.exp2_.value_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing EXP!\n");
    exit(1);
  }
}

void ppSE(SE p, int _i_)
{
  switch(p->kind)
  {
  case is_SE1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("SE");
    renderS("BAH");
    renderC('(');
    ppOPL(p->u.se1_.opl_, 0);
    renderC(')');
    ppBlock(p->u.se1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SE2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("SE");
    renderS("BAH");
    renderC('(');
    ppOPL(p->u.se2_.opl_, 0);
    renderC(')');
    ppBlock(p->u.se2_.block_1, 0);
    renderS("TCHE");
    ppBlock(p->u.se2_.block_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SE!\n");
    exit(1);
  }
}

void ppOPerL(OPerL p, int _i_)
{
  switch(p->kind)
  {
  case is_OPerL1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL4:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL5:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("==");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL6:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<>");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OPerL!\n");
    exit(1);
  }
}

void ppOPerA(OPerA p, int _i_)
{
  switch(p->kind)
  {
  case is_OPerA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('/');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerA2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('*');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerA3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('+');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerA4:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('-');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OPerA!\n");
    exit(1);
  }
}

void ppOPL(OPL p, int _i_)
{
  switch(p->kind)
  {
  case is_OPL1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVALUE(p->u.opl1_.value_1, 0);
    ppOPerL(p->u.opl1_.operl_, 0);
    ppVALUE(p->u.opl1_.value_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OPL!\n");
    exit(1);
  }
}

void ppCLAUDDIZ(CLAUDDIZ p, int _i_)
{
  switch(p->kind)
  {
  case is_CLAUDDIZ1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("ClaudDiz");
    renderC('(');
    ppVALUE(p->u.clauddiz1_.value_, 0);
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CLAUDDIZ!\n");
    exit(1);
  }
}

void ppRECEBA(RECEBA p, int _i_)
{
  switch(p->kind)
  {
  case is_RECEBA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Receba");
    renderC('(');
    ppType(p->u.receba1_.type_, 0);
    ppIdent(p->u.receba1_.ident_, 0);
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RECEBA!\n");
    exit(1);
  }
}

void ppATE(ATE p, int _i_)
{
  switch(p->kind)
  {
  case is_ATE1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("ATE");
    renderC('(');
    ppOPL(p->u.ate1_.opl_, 0);
    renderC(')');
    ppBlock(p->u.ate1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ATE!\n");
    exit(1);
  }
}

void ppFAZAI(FAZAI p, int _i_)
{
  switch(p->kind)
  {
  case is_FAZAI1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("FAZAI");
    renderC('(');
    ppType(p->u.fazai1_.type_, 0);
    ppIdent(p->u.fazai1_.ident_, 0);
    renderC('=');
    ppVALUE(p->u.fazai1_.value_, 0);
    renderC('|');
    ppOPL(p->u.fazai1_.opl_, 0);
    renderC('|');
    ppInteger(p->u.fazai1_.integer_, 0);
    renderC(')');
    ppBlock(p->u.fazai1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FAZAI!\n");
    exit(1);
  }
}

void ppVALUE(VALUE p, int _i_)
{
  switch(p->kind)
  {
  case is_VALUEIdent:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.valueident_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUEString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.valuestring_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUEInteger:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.valueinteger_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUEDouble:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.valuedouble_.double_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VALUE!\n");
    exit(1);
  }
}

void ppType(Type p, int _i_)
{
  switch(p->kind)
  {
  case is_Type_interu:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("interu");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_floaty:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("floaty");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_stringo:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("stringo");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void ppVET(VET p, int _i_)
{
  switch(p->kind)
  {
  case is_VET1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.vet1_.type_, 0);
    ppIdent(p->u.vet1_.ident_, 0);
    renderC('[');
    ppInteger(p->u.vet1_.integer_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VET2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("int");
    ppIdent(p->u.vet2_.ident_, 0);
    renderC('[');
    ppInteger(p->u.vet2_.integer_, 0);
    renderC(']');
    renderC('=');
    renderC('[');
    ppConjInt(p->u.vet2_.conjint_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VET3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("float");
    ppIdent(p->u.vet3_.ident_, 0);
    renderC('[');
    ppInteger(p->u.vet3_.integer_, 0);
    renderC(']');
    renderC('=');
    renderC('[');
    ppConjReal(p->u.vet3_.conjreal_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VET4:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("string");
    ppIdent(p->u.vet4_.ident_, 0);
    renderC('[');
    ppInteger(p->u.vet4_.integer_, 0);
    renderC(']');
    renderC('=');
    renderC('[');
    ppConjString(p->u.vet4_.conjstring_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VET!\n");
    exit(1);
  }
}

void ppSTRUCT(STRUCT p, int _i_)
{
  switch(p->kind)
  {
  case is_STRUCT1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("ISTRUCT");
    renderC('[');
    ppInteger(p->u.struct1_.integer_, 0);
    renderC(']');
    renderC('=');
    renderC('{');
    ppHeteroElements(p->u.struct1_.heteroelements_, 0);
    renderC('}');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing STRUCT!\n");
    exit(1);
  }
}

void ppHeteroElements(HeteroElements p, int _i_)
{
  switch(p->kind)
  {
  case is_HeteroElementsHeteroElement:
    if (_i_ > 0) renderC(_L_PAREN);
    ppHeteroElement(p->u.heteroelementsheteroelement_.heteroelement_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_HeteroElements1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppHeteroElement(p->u.heteroelements1_.heteroelement_, 0);
    renderC(',');
    ppHeteroElements(p->u.heteroelements1_.heteroelements_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing HeteroElements!\n");
    exit(1);
  }
}

void ppHeteroElement(HeteroElement p, int _i_)
{
  switch(p->kind)
  {
  case is_HeteroElementString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.heteroelementstring_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_HeteroElementDouble:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.heteroelementdouble_.double_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_HeteroElementInteger:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.heteroelementinteger_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing HeteroElement!\n");
    exit(1);
  }
}

void ppFUNC(FUNC p, int _i_)
{
  switch(p->kind)
  {
  case is_FUNC1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("FUNC");
    ppIdent(p->u.func1_.ident_, 0);
    renderC('(');
    renderC(')');
    ppBlock(p->u.func1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FUNC!\n");
    exit(1);
  }
}

void ppGOTO(GOTO p, int _i_)
{
  switch(p->kind)
  {
  case is_GOTO1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("GOTO");
    ppInteger(p->u.goto1_.integer_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing GOTO!\n");
    exit(1);
  }
}

void ppLABEL(LABEL p, int _i_)
{
  switch(p->kind)
  {
  case is_LABEL1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("LABEL");
    ppInteger(p->u.label1_.integer_, 0);
    renderC(':');
    ppBlock(p->u.label1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LABEL!\n");
    exit(1);
  }
}

void ppConjInt(ConjInt p, int _i_)
{
  switch(p->kind)
  {
  case is_ConjIntInteger:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.conjintinteger_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConjInt1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.conjint1_.integer_, 0);
    renderC(',');
    ppConjInt(p->u.conjint1_.conjint_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConjInt!\n");
    exit(1);
  }
}

void ppConjReal(ConjReal p, int _i_)
{
  switch(p->kind)
  {
  case is_ConjRealDouble:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.conjrealdouble_.double_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConjReal1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.conjreal1_.double_, 0);
    renderC(',');
    ppConjReal(p->u.conjreal1_.conjreal_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConjReal!\n");
    exit(1);
  }
}

void ppConjString(ConjString p, int _i_)
{
  switch(p->kind)
  {
  case is_ConjStringString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.conjstringstring_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConjString1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.conjstring1_.string_, 0);
    renderC(',');
    ppConjString(p->u.conjstring1_.conjstring_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConjString!\n");
    exit(1);
  }
}

void ppCONST(CONST p, int _i_)
{
  switch(p->kind)
  {
  case is_LConst:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("CONST");
    ppType(p->u.lconst_.type_, 0);
    ppIdent(p->u.lconst_.ident_, 0);
    renderC('=');
    ppVALUE(p->u.lconst_.value_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CONST!\n");
    exit(1);
  }
}

void ppPOINT(POINT p, int _i_)
{
  switch(p->kind)
  {
  case is_LPoint:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.lpoint_.type_, 0);
    renderC('*');
    ppIdent(p->u.lpoint_.ident_1, 0);
    renderC('=');
    ppIdent(p->u.lpoint_.ident_2, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing POINT!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shS(S p)
{
  switch(p->kind)
  {
  case is_Sst:
    bufAppendC('(');

    bufAppendS("Sst");

    bufAppendC(' ');

    shBlock(p->u.sst_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing S!\n");
    exit(1);
  }
}

void shBlock(Block p)
{
  switch(p->kind)
  {
  case is_LBlock:
    bufAppendC('(');

    bufAppendS("LBlock");

    bufAppendC(' ');

    shCMDS(p->u.lblock_.cmds_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Block!\n");
    exit(1);
  }
}

void shCMDS(CMDS p)
{
  switch(p->kind)
  {
  case is_CMDSCMD:
    bufAppendC('(');

    bufAppendS("CMDSCMD");

    bufAppendC(' ');

    shCMD(p->u.cmdscmd_.cmd_);

    bufAppendC(')');

    break;
  case is_CMDS1:
    bufAppendC('(');

    bufAppendS("CMDS1");

    bufAppendC(' ');

    shCMD(p->u.cmds1_.cmd_);
  bufAppendC(' ');
    shCMDS(p->u.cmds1_.cmds_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CMDS!\n");
    exit(1);
  }
}

void shCMD(CMD p)
{
  switch(p->kind)
  {
  case is_CMDATB:
    bufAppendC('(');

    bufAppendS("CMDATB");

    bufAppendC(' ');

    shATB(p->u.cmdatb_.atb_);

    bufAppendC(')');

    break;
  case is_CMDSE:
    bufAppendC('(');

    bufAppendS("CMDSE");

    bufAppendC(' ');

    shSE(p->u.cmdse_.se_);

    bufAppendC(')');

    break;
  case is_CMDATE:
    bufAppendC('(');

    bufAppendS("CMDATE");

    bufAppendC(' ');

    shATE(p->u.cmdate_.ate_);

    bufAppendC(')');

    break;
  case is_CMDFAZAI:
    bufAppendC('(');

    bufAppendS("CMDFAZAI");

    bufAppendC(' ');

    shFAZAI(p->u.cmdfazai_.fazai_);

    bufAppendC(')');

    break;
  case is_CMDCLAUDDIZ:
    bufAppendC('(');

    bufAppendS("CMDCLAUDDIZ");

    bufAppendC(' ');

    shCLAUDDIZ(p->u.cmdclauddiz_.clauddiz_);

    bufAppendC(')');

    break;
  case is_CMDRECEBA:
    bufAppendC('(');

    bufAppendS("CMDRECEBA");

    bufAppendC(' ');

    shRECEBA(p->u.cmdreceba_.receba_);

    bufAppendC(')');

    break;
  case is_CMDCONST:
    bufAppendC('(');

    bufAppendS("CMDCONST");

    bufAppendC(' ');

    shCONST(p->u.cmdconst_.const_);

    bufAppendC(')');

    break;
  case is_CMDVET:
    bufAppendC('(');

    bufAppendS("CMDVET");

    bufAppendC(' ');

    shVET(p->u.cmdvet_.vet_);

    bufAppendC(')');

    break;
  case is_CMDFUNC:
    bufAppendC('(');

    bufAppendS("CMDFUNC");

    bufAppendC(' ');

    shFUNC(p->u.cmdfunc_.func_);

    bufAppendC(')');

    break;
  case is_CMDGOTO:
    bufAppendC('(');

    bufAppendS("CMDGOTO");

    bufAppendC(' ');

    shGOTO(p->u.cmdgoto_.goto_);

    bufAppendC(')');

    break;
  case is_CMDLABEL:
    bufAppendC('(');

    bufAppendS("CMDLABEL");

    bufAppendC(' ');

    shLABEL(p->u.cmdlabel_.label_);

    bufAppendC(')');

    break;
  case is_CMDSTRUCT:
    bufAppendC('(');

    bufAppendS("CMDSTRUCT");

    bufAppendC(' ');

    shSTRUCT(p->u.cmdstruct_.struct_);

    bufAppendC(')');

    break;
  case is_CMDPOINT:
    bufAppendC('(');

    bufAppendS("CMDPOINT");

    bufAppendC(' ');

    shPOINT(p->u.cmdpoint_.point_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CMD!\n");
    exit(1);
  }
}

void shATB(ATB p)
{
  switch(p->kind)
  {
  case is_ATB1:
    bufAppendC('(');

    bufAppendS("ATB1");

    bufAppendC(' ');

    shType(p->u.atb1_.type_);
  bufAppendC(' ');
    shIdent(p->u.atb1_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.atb1_.value_);

    bufAppendC(')');

    break;
  case is_ATB2:
    bufAppendC('(');

    bufAppendS("ATB2");

    bufAppendC(' ');

    shType(p->u.atb2_.type_);
  bufAppendC(' ');
    shIdent(p->u.atb2_.ident_);
  bufAppendC(' ');
    shEXP(p->u.atb2_.exp_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ATB!\n");
    exit(1);
  }
}

void shEXP(EXP p)
{
  switch(p->kind)
  {
  case is_EXP1:
    bufAppendC('(');

    bufAppendS("EXP1");

    bufAppendC(' ');

    shVALUE(p->u.exp1_.value_1);
  bufAppendC(' ');
    shOPerA(p->u.exp1_.opera_);
  bufAppendC(' ');
    shVALUE(p->u.exp1_.value_2);

    bufAppendC(')');

    break;
  case is_EXP2:
    bufAppendC('(');

    bufAppendS("EXP2");

    bufAppendC(' ');

    shEXP(p->u.exp2_.exp_);
  bufAppendC(' ');
    shOPerA(p->u.exp2_.opera_);
  bufAppendC(' ');
    shVALUE(p->u.exp2_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing EXP!\n");
    exit(1);
  }
}

void shSE(SE p)
{
  switch(p->kind)
  {
  case is_SE1:
    bufAppendC('(');

    bufAppendS("SE1");

    bufAppendC(' ');

    shOPL(p->u.se1_.opl_);
  bufAppendC(' ');
    shBlock(p->u.se1_.block_);

    bufAppendC(')');

    break;
  case is_SE2:
    bufAppendC('(');

    bufAppendS("SE2");

    bufAppendC(' ');

    shOPL(p->u.se2_.opl_);
  bufAppendC(' ');
    shBlock(p->u.se2_.block_1);
  bufAppendC(' ');
    shBlock(p->u.se2_.block_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SE!\n");
    exit(1);
  }
}

void shOPerL(OPerL p)
{
  switch(p->kind)
  {
  case is_OPerL1:

    bufAppendS("OPerL1");




    break;
  case is_OPerL2:

    bufAppendS("OPerL2");




    break;
  case is_OPerL3:

    bufAppendS("OPerL3");




    break;
  case is_OPerL4:

    bufAppendS("OPerL4");




    break;
  case is_OPerL5:

    bufAppendS("OPerL5");




    break;
  case is_OPerL6:

    bufAppendS("OPerL6");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OPerL!\n");
    exit(1);
  }
}

void shOPerA(OPerA p)
{
  switch(p->kind)
  {
  case is_OPerA1:

    bufAppendS("OPerA1");




    break;
  case is_OPerA2:

    bufAppendS("OPerA2");




    break;
  case is_OPerA3:

    bufAppendS("OPerA3");




    break;
  case is_OPerA4:

    bufAppendS("OPerA4");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OPerA!\n");
    exit(1);
  }
}

void shOPL(OPL p)
{
  switch(p->kind)
  {
  case is_OPL1:
    bufAppendC('(');

    bufAppendS("OPL1");

    bufAppendC(' ');

    shVALUE(p->u.opl1_.value_1);
  bufAppendC(' ');
    shOPerL(p->u.opl1_.operl_);
  bufAppendC(' ');
    shVALUE(p->u.opl1_.value_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OPL!\n");
    exit(1);
  }
}

void shCLAUDDIZ(CLAUDDIZ p)
{
  switch(p->kind)
  {
  case is_CLAUDDIZ1:
    bufAppendC('(');

    bufAppendS("CLAUDDIZ1");

    bufAppendC(' ');

    shVALUE(p->u.clauddiz1_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CLAUDDIZ!\n");
    exit(1);
  }
}

void shRECEBA(RECEBA p)
{
  switch(p->kind)
  {
  case is_RECEBA1:
    bufAppendC('(');

    bufAppendS("RECEBA1");

    bufAppendC(' ');

    shType(p->u.receba1_.type_);
  bufAppendC(' ');
    shIdent(p->u.receba1_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RECEBA!\n");
    exit(1);
  }
}

void shATE(ATE p)
{
  switch(p->kind)
  {
  case is_ATE1:
    bufAppendC('(');

    bufAppendS("ATE1");

    bufAppendC(' ');

    shOPL(p->u.ate1_.opl_);
  bufAppendC(' ');
    shBlock(p->u.ate1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ATE!\n");
    exit(1);
  }
}

void shFAZAI(FAZAI p)
{
  switch(p->kind)
  {
  case is_FAZAI1:
    bufAppendC('(');

    bufAppendS("FAZAI1");

    bufAppendC(' ');

    shType(p->u.fazai1_.type_);
  bufAppendC(' ');
    shIdent(p->u.fazai1_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.fazai1_.value_);
  bufAppendC(' ');
    shOPL(p->u.fazai1_.opl_);
  bufAppendC(' ');
    shInteger(p->u.fazai1_.integer_);
  bufAppendC(' ');
    shBlock(p->u.fazai1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FAZAI!\n");
    exit(1);
  }
}

void shVALUE(VALUE p)
{
  switch(p->kind)
  {
  case is_VALUEIdent:
    bufAppendC('(');

    bufAppendS("VALUEIdent");

    bufAppendC(' ');

    shIdent(p->u.valueident_.ident_);

    bufAppendC(')');

    break;
  case is_VALUEString:
    bufAppendC('(');

    bufAppendS("VALUEString");

    bufAppendC(' ');

    shString(p->u.valuestring_.string_);

    bufAppendC(')');

    break;
  case is_VALUEInteger:
    bufAppendC('(');

    bufAppendS("VALUEInteger");

    bufAppendC(' ');

    shInteger(p->u.valueinteger_.integer_);

    bufAppendC(')');

    break;
  case is_VALUEDouble:
    bufAppendC('(');

    bufAppendS("VALUEDouble");

    bufAppendC(' ');

    shDouble(p->u.valuedouble_.double_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing VALUE!\n");
    exit(1);
  }
}

void shType(Type p)
{
  switch(p->kind)
  {
  case is_Type_interu:

    bufAppendS("Type_interu");




    break;
  case is_Type_floaty:

    bufAppendS("Type_floaty");




    break;
  case is_Type_stringo:

    bufAppendS("Type_stringo");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Type!\n");
    exit(1);
  }
}

void shVET(VET p)
{
  switch(p->kind)
  {
  case is_VET1:
    bufAppendC('(');

    bufAppendS("VET1");

    bufAppendC(' ');

    shType(p->u.vet1_.type_);
  bufAppendC(' ');
    shIdent(p->u.vet1_.ident_);
  bufAppendC(' ');
    shInteger(p->u.vet1_.integer_);

    bufAppendC(')');

    break;
  case is_VET2:
    bufAppendC('(');

    bufAppendS("VET2");

    bufAppendC(' ');

    shIdent(p->u.vet2_.ident_);
  bufAppendC(' ');
    shInteger(p->u.vet2_.integer_);
  bufAppendC(' ');
    shConjInt(p->u.vet2_.conjint_);

    bufAppendC(')');

    break;
  case is_VET3:
    bufAppendC('(');

    bufAppendS("VET3");

    bufAppendC(' ');

    shIdent(p->u.vet3_.ident_);
  bufAppendC(' ');
    shInteger(p->u.vet3_.integer_);
  bufAppendC(' ');
    shConjReal(p->u.vet3_.conjreal_);

    bufAppendC(')');

    break;
  case is_VET4:
    bufAppendC('(');

    bufAppendS("VET4");

    bufAppendC(' ');

    shIdent(p->u.vet4_.ident_);
  bufAppendC(' ');
    shInteger(p->u.vet4_.integer_);
  bufAppendC(' ');
    shConjString(p->u.vet4_.conjstring_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing VET!\n");
    exit(1);
  }
}

void shSTRUCT(STRUCT p)
{
  switch(p->kind)
  {
  case is_STRUCT1:
    bufAppendC('(');

    bufAppendS("STRUCT1");

    bufAppendC(' ');

    shInteger(p->u.struct1_.integer_);
  bufAppendC(' ');
    shHeteroElements(p->u.struct1_.heteroelements_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing STRUCT!\n");
    exit(1);
  }
}

void shHeteroElements(HeteroElements p)
{
  switch(p->kind)
  {
  case is_HeteroElementsHeteroElement:
    bufAppendC('(');

    bufAppendS("HeteroElementsHeteroElement");

    bufAppendC(' ');

    shHeteroElement(p->u.heteroelementsheteroelement_.heteroelement_);

    bufAppendC(')');

    break;
  case is_HeteroElements1:
    bufAppendC('(');

    bufAppendS("HeteroElements1");

    bufAppendC(' ');

    shHeteroElement(p->u.heteroelements1_.heteroelement_);
  bufAppendC(' ');
    shHeteroElements(p->u.heteroelements1_.heteroelements_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing HeteroElements!\n");
    exit(1);
  }
}

void shHeteroElement(HeteroElement p)
{
  switch(p->kind)
  {
  case is_HeteroElementString:
    bufAppendC('(');

    bufAppendS("HeteroElementString");

    bufAppendC(' ');

    shString(p->u.heteroelementstring_.string_);

    bufAppendC(')');

    break;
  case is_HeteroElementDouble:
    bufAppendC('(');

    bufAppendS("HeteroElementDouble");

    bufAppendC(' ');

    shDouble(p->u.heteroelementdouble_.double_);

    bufAppendC(')');

    break;
  case is_HeteroElementInteger:
    bufAppendC('(');

    bufAppendS("HeteroElementInteger");

    bufAppendC(' ');

    shInteger(p->u.heteroelementinteger_.integer_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing HeteroElement!\n");
    exit(1);
  }
}

void shFUNC(FUNC p)
{
  switch(p->kind)
  {
  case is_FUNC1:
    bufAppendC('(');

    bufAppendS("FUNC1");

    bufAppendC(' ');

    shIdent(p->u.func1_.ident_);
  bufAppendC(' ');
    shBlock(p->u.func1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FUNC!\n");
    exit(1);
  }
}

void shGOTO(GOTO p)
{
  switch(p->kind)
  {
  case is_GOTO1:
    bufAppendC('(');

    bufAppendS("GOTO1");

    bufAppendC(' ');

    shInteger(p->u.goto1_.integer_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing GOTO!\n");
    exit(1);
  }
}

void shLABEL(LABEL p)
{
  switch(p->kind)
  {
  case is_LABEL1:
    bufAppendC('(');

    bufAppendS("LABEL1");

    bufAppendC(' ');

    shInteger(p->u.label1_.integer_);
  bufAppendC(' ');
    shBlock(p->u.label1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing LABEL!\n");
    exit(1);
  }
}

void shConjInt(ConjInt p)
{
  switch(p->kind)
  {
  case is_ConjIntInteger:
    bufAppendC('(');

    bufAppendS("ConjIntInteger");

    bufAppendC(' ');

    shInteger(p->u.conjintinteger_.integer_);

    bufAppendC(')');

    break;
  case is_ConjInt1:
    bufAppendC('(');

    bufAppendS("ConjInt1");

    bufAppendC(' ');

    shInteger(p->u.conjint1_.integer_);
  bufAppendC(' ');
    shConjInt(p->u.conjint1_.conjint_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ConjInt!\n");
    exit(1);
  }
}

void shConjReal(ConjReal p)
{
  switch(p->kind)
  {
  case is_ConjRealDouble:
    bufAppendC('(');

    bufAppendS("ConjRealDouble");

    bufAppendC(' ');

    shDouble(p->u.conjrealdouble_.double_);

    bufAppendC(')');

    break;
  case is_ConjReal1:
    bufAppendC('(');

    bufAppendS("ConjReal1");

    bufAppendC(' ');

    shDouble(p->u.conjreal1_.double_);
  bufAppendC(' ');
    shConjReal(p->u.conjreal1_.conjreal_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ConjReal!\n");
    exit(1);
  }
}

void shConjString(ConjString p)
{
  switch(p->kind)
  {
  case is_ConjStringString:
    bufAppendC('(');

    bufAppendS("ConjStringString");

    bufAppendC(' ');

    shString(p->u.conjstringstring_.string_);

    bufAppendC(')');

    break;
  case is_ConjString1:
    bufAppendC('(');

    bufAppendS("ConjString1");

    bufAppendC(' ');

    shString(p->u.conjstring1_.string_);
  bufAppendC(' ');
    shConjString(p->u.conjstring1_.conjstring_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ConjString!\n");
    exit(1);
  }
}

void shCONST(CONST p)
{
  switch(p->kind)
  {
  case is_LConst:
    bufAppendC('(');

    bufAppendS("LConst");

    bufAppendC(' ');

    shType(p->u.lconst_.type_);
  bufAppendC(' ');
    shIdent(p->u.lconst_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.lconst_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CONST!\n");
    exit(1);
  }
}

void shPOINT(POINT p)
{
  switch(p->kind)
  {
  case is_LPoint:
    bufAppendC('(');

    bufAppendS("LPoint");

    bufAppendC(' ');

    shType(p->u.lpoint_.type_);
  bufAppendC(' ');
    shIdent(p->u.lpoint_.ident_1);
  bufAppendC(' ');
    shIdent(p->u.lpoint_.ident_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing POINT!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

